import type { MockEmail } from "./mock-emails";

const now = new Date();
const minsAgo = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600_000).toISOString();

// Each click of "Sync" pulls the next batch — simulates Gmail's incremental fetch.
export const syncBatches: MockEmail[][] = [
  [
    {
      id: "s1",
      from: "Aarav Singh",
      fromEmail: "aarav@northwind.io",
      subject: "Staging cluster access granted",
      preview: "You now have admin access to staging-2. Token expires in 7 days.",
      body: "Hey, I granted you admin on staging-2. The token expires in 7 days, rotate before Friday.",
      receivedAt: minsAgo(12),
      unread: true,
      priority: "high",
      attentionScore: 74,
      category: "Work",
      summary: "Staging-2 admin access granted. Rotate token before Friday (expires in 7 days).",
      tasks: [{ text: "Rotate staging-2 token before Friday", done: false }],
      deadline: { label: "Friday", dueAt: hoursFromNow(96) },
      sentiment: "neutral",
    },
    {
      id: "s2",
      from: "Linear",
      fromEmail: "notifications@linear.app",
      subject: "3 issues assigned to you in MAIL project",
      preview: "MAIL-118, MAIL-122, MAIL-125 assigned this morning.",
      body: "3 issues were assigned to you: MAIL-118 (bug), MAIL-122 (feature), MAIL-125 (chore).",
      receivedAt: minsAgo(24),
      unread: true,
      priority: "medium",
      attentionScore: 48,
      category: "Work",
      summary: "3 new Linear issues assigned to you in MAIL project.",
      tasks: [{ text: "Triage MAIL-118 / 122 / 125", done: false }],
      sentiment: "neutral",
    },
  ],
  [
    {
      id: "s3",
      from: "CEO — Maya Iyer",
      fromEmail: "maya@northwind.io",
      subject: "URGENT: Q4 numbers need correction before board call",
      preview: "Board call is at 4 PM. Revenue slide has wrong figure — fix ASAP.",
      body: "The revenue figure on slide 12 is off by $200k. Please correct it before the 4 PM board call today. This cannot wait.",
      receivedAt: minsAgo(6),
      unread: true,
      priority: "critical",
      attentionScore: 98,
      category: "Work",
      summary: "Revenue figure on slide 12 is wrong. Fix before 4 PM board call today.",
      tasks: [
        { text: "Correct revenue figure on slide 12", done: false },
        { text: "Re-send deck before 4 PM", done: false },
      ],
      deadline: { label: "Today 4:00 PM", dueAt: hoursFromNow(3) },
      sentiment: "urgent",
    },
    {
      id: "s4",
      from: "Airbnb",
      fromEmail: "no-reply@airbnb.com",
      subject: "Your trip to Lisbon is confirmed",
      preview: "Check-in Dec 12. Reservation HMRBN42.",
      body: "Your reservation is confirmed. Check-in Dec 12, check-out Dec 18. Host: Sofia.",
      receivedAt: minsAgo(30),
      unread: true,
      priority: "low",
      attentionScore: 28,
      category: "Travel",
      summary: "Lisbon trip confirmed — check-in Dec 12, host Sofia.",
      tasks: [],
      sentiment: "positive",
    },
  ],
  [
    {
      id: "s5",
      from: "Slack",
      fromEmail: "notify@slack.com",
      subject: "8 new mentions in #incidents",
      preview: "@you was mentioned 8 times in the last hour.",
      body: "You were mentioned 8 times in #incidents in the last hour. Looks like a brewing P1.",
      receivedAt: minsAgo(8),
      unread: true,
      priority: "high",
      attentionScore: 76,
      category: "Work",
      summary: "8 mentions in #incidents in the last hour — likely a P1 brewing.",
      tasks: [{ text: "Check #incidents for live P1", done: false }],
      sentiment: "urgent",
    },
    {
      id: "s6",
      from: "Zoom",
      fromEmail: "no-reply@zoom.us",
      subject: "Cloud recording ready: 1:1 with Rohan",
      preview: "Your recording from yesterday is ready (32 min).",
      body: "Your cloud recording of '1:1 with Rohan' is ready. Duration 32 min. Auto-deletes in 14 days.",
      receivedAt: minsAgo(45),
      unread: true,
      priority: "low",
      attentionScore: 20,
      category: "Work",
      summary: "Zoom recording of 1:1 with Rohan ready. Auto-deletes in 14 days.",
      tasks: [],
      sentiment: "neutral",
    },
  ],
  [
    {
      id: "s7",
      from: "Wise",
      fromEmail: "noreply@wise.com",
      subject: "You received $4,200.00 from PartnerCo",
      preview: "Funds available in your USD balance.",
      body: "$4,200.00 received from PartnerCo (invoice INV-882). Funds available in your USD balance.",
      receivedAt: minsAgo(15),
      unread: true,
      priority: "medium",
      attentionScore: 55,
      category: "Finance",
      summary: "$4,200 received from PartnerCo for INV-882. Funds available.",
      tasks: [{ text: "Mark INV-882 paid in books", done: false }],
      sentiment: "positive",
    },
    {
      id: "s8",
      from: "support@bonus-rewards-claim.co",
      fromEmail: "support@bonus-rewards-claim.co",
      subject: "Final notice: $500 Amazon gift card pending",
      preview: "Claim within 1 hour or it expires forever.",
      body: "Hello winner!! Your $500 Amazon gift card is waiting. Click here within 1 hour: http://tinyurl.com/claim-bonus",
      receivedAt: minsAgo(50),
      unread: true,
      priority: "low",
      attentionScore: 5,
      category: "Promotions",
      summary: "Phishing — fake reward, urgency, shortened link. Do not click.",
      tasks: [],
      spam: true,
      sentiment: "urgent",
    },
  ],
];
